### ISSUE TITLE
Allow specifying game path manually

### ISSUE THREAD

**Issue by Artalus** [soler91/noita-together#10]
I kinda believe no autodetection can cover all the ways the user can mess with the game folder. Be it moving the folder via Steam itself, or simply reinstalling Windows with games sitting on another drive. So instead, why not simply allow the user to specify the location?

I looked at the code - it might require shuffling the update sequence a bit, so NT won't start downloading things before the game path is set, but it seems doable. Provide a `vInput` and `vButton` at the `Update` form, and once it points to a correct location - post a message to the event loop with said location. Current search mechanism can be used to pre-fill said input with values from Registry (or some Steam metadata, if possible), and clicking the "confirm path" button can validate that there is indeed a `noita.exe` inside.

**Comment by soler91** [comment]
adressed in 4712f723881eaee63e97abbd3561f9c3609d0410
expect app update later today
