### ISSUE TITLE
doesnt launch on ubuntu

### ISSUE THREAD

**Issue by Thoro1** [soler91/noita-together#100]
this is the terminal output when i try to run the file:

$ ./Noita.Together-0.9.40.AppImage 
Checking for update
(node:11272) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Update for version 0.9.40 is not available (latest version: 0.9.40, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[11272:0416/130538.842155:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

**Comment by soler91** [comment]
From the releases download page:

> Linux: Noita Together-0.9.40.AppImage if you are running linux (i dont know what im doing here) might need to run it with "--no-sandbox"
