### ISSUE TITLE
[Feature] random seed setting

### ISSUE THREAD

**Issue by clragon** [soler91/noita-together#12]
**Is your feature request related to a problem? Please describe.**
I like to play with friends on set seed, 
but this requires me to change the seed manually after every run
and come up with numbers.

**Describe the solution you'd like**
it would be nice if there was a button to generate a random seed for you in the settings.
maybe random set seed could even be a checkbox where the app will automatically change to a new random seed after the run ended.

**Comment by soler91** [comment]
Partially adressed in 27cb2ae3dd58f9d9891281e880f4246f1cb23f0b
will see about making it completely automatic later on

expect update later today
