### ISSUE TITLE
Wont connect to twitch

### ISSUE THREAD

**Issue by Syd4r** [soler91/noita-together#13]
After I click the "Login with Twitch.tv" button, there's just an infinitely rotating loading circle
![Screenshot (164)](https://user-images.githubusercontent.com/72267789/107711781-31b87b00-6c96-11eb-8014-d414b3b55b90.png)

**Comment by Syd4r** [comment]
welp, my friend gave me the link that the button sent him to, I pasted that into my chrome and it worked

**Comment by soler91** [comment]
it doesnt open your browser when you click on it ?
