### ISSUE TITLE
[BUG] extra life perk is ignored

### ISSUE THREAD

**Issue by clragon** [soler91/noita-together#15]
**Describe the bug**
When using the extra life perk, the mod players will not respawn, but instead just die and the run ends.

**To Reproduce**
- create a lobby
- set death penatly to run end
- pick up extra life perk
- die

**What is the current behavior?**
the run is ended and all players die

**Expected behavior**
the player that has the perk should be respawned and continue the run with 100 health,
deactivating the perk in the process.

**Which versions of noita together are affected by this issue?**
tested on v0.9.19

**Comment by soler91** [comment]
Just went in game, followed those steps and the run did not end after "dying" and got my hp back to 100 working as intended... are you on the game's beta branch ?

**Comment by clragon** [comment]
no, I we were playing on stable 🤔

**Comment by soler91** [comment]
how many times did you reproduce it ?

**Comment by clragon** [comment]
we've only encountered it once, I think I will report back if this happens again and try to take a closer look at the circumstances. 
I havent actively tried to trigger it yet, my bad.
