### ISSUE TITLE
Game is running really slow after v0.9.20

### ISSUE THREAD

**Issue by hambread** [soler91/noita-together#17]
The game was running fine until the app auto-updated. After that, the game ran really slowly whenever I enabled the mod. I've tried restarting both the app and Noita. I even reinstalled the mod. I'm running the Dec 1 2020 build and I'm not in the beta. What can I do to fix this? Thanks!

**Comment by soler91** [comment]
check for a file called logger.txt in your noita folder (while the game is running slow) then if its not empty upload it to pastebin and link here

**Comment by zhenka00** [comment]
Same problem. Together now is unplayable. Cursor and everything is on lag.

**Comment by clragon** [comment]
Also having a friend that has this problem right now. Enabling the mod will cause his entire game to lag beyond reason. 
His logger file: [logger.txt](https://github.com/soler91/noita-together/files/6016018/logger.txt)

**Comment by HereForNoitaTogether** [comment]
[logger.txt](https://github.com/soler91/noita-together/files/6016376/logger.txt)
Here is my logger file also. Went to launch the game and noita together with a friend today and we are both at ~30 fps making the game run half speed... We tried relaunching Noita Together and Noita and couldn't get it to work any better.

**Comment by Plazmaic** [comment]
I'm having the same issue ill drop, my logger, here as well. my friend wasn't experiencing any lag for some reason though.
[Noita Together Lag Logger file.txt](https://github.com/soler91/noita-together/files/6016584/Noita.Together.Lag.Logger.file.txt)

**Comment by soler91** [comment]
Should be fixed now

there was some unused code that might somehow only work on beta at the moment
dece6bb91d49e3f1beea1e4a7a35a616081e4f70

**Comment by BIackHornet** [comment]
Thanks, this is fixed for me now.

**Comment by hambread** [comment]
Thanks a bunch! It's fixed for me now too.
