### ISSUE TITLE
[UI feature] Lobby closing confirmation pop-up

### ISSUE THREAD

**Issue by BastiaanBekooij** [soler91/noita-together#19]
When I first used the app, I closed the lobby by accident a few times, because I wanted to see if other lobbies got opened. I think there are three ways to make this more user friendly:
1. A pop-up that asks for confirmation that you want to close the lobby.
2. The back button has a clear text.
3. Going back doesn't close the lobby and shows you which other lobbies are open. (Could also be a separate button)

**Comment by soler91** [comment]
confirmation has been added for a while, forgot to close
