### ISSUE TITLE
[bug] Random seed button

### ISSUE THREAD

**Issue by BastiaanBekooij** [soler91/noita-together#20]
Note: I didn't get to check this in the latest update. 

When using the random seed button the seed is not changing for everyone or even the host itself. I experienced this myself, but also saw it on Chereazis stream.

Interestingly it does work when you type in a seed yourself. This might mean that your cursor must have been in the seed field?

**Comment by clragon** [comment]
I am definitely also experiencing this. 
If you select the seed field then click apply, it seems to work 100% of the time.

**Comment by soler91** [comment]
been fixed for a while, forgot to close
