### ISSUE TITLE
[Bug] Won't log in into Twitch

### ISSUE THREAD

**Issue by MaxBoi342** [soler91/noita-together#21]
So I installed the mod, clicked the log in with Twitch button, it opened the link in a browser (Edge do be exact, even though Chrome is my default). 
Logged in, pressed the authorize button and nothing happened. Clicked it a few times. Closed the browser, opened the link again, clicked the Authotize button a few more times, still doesn't work.
Then I close the app and open it again, and now the link doesnt load the Twitch log in page anymore, just blank.
![image](https://user-images.githubusercontent.com/79421296/108637162-ba4ecc80-7489-11eb-8544-104f8391e0a0.png)
Reinstalling didn't change anything.

**Comment by soler91** [comment]
Seems like the app is not registering the custom protocol that prompts the browser to launch the app
Do you run windows 10 ?
if you do, is it just "10" or "10 S" ?

**Comment by MaxBoi342** [comment]
I run Windows 10, no S

**Comment by soler91** [comment]
your windows user account needs to be an administrator
