### ISSUE TITLE
"There were errors when initializing following mods: noita-together"

### ISSUE THREAD

**Issue by darkblue12342** [soler91/noita-together#23]
Although all my files seem to be in place and smooth installation, it won´t run. When hosting and when having joined a room it will declare me as "not ready", even tho I am ingame. The message in the title consistently shows up upon entering the world.
![20210222233123_1](https://user-images.githubusercontent.com/79484605/108780007-14be5a80-7568-11eb-9dbc-7adf368b5b71.jpg)
![Unbenannt](https://user-images.githubusercontent.com/79484605/108780023-1b4cd200-7568-11eb-9e07-67366588ab16.PNG)

**Comment by soler91** [comment]
go to your noita folder and upload  file called logger.txt make sure you had just gotten that message and not opened the game again because it clears the log

**Comment by darkblue12342** [comment]
[logger.txt](https://github.com/soler91/noita-together/files/6025722/logger.txt)

**Comment by soler91** [comment]
seems your antivirus or something else is deleting the bin folder in the noita-together mod folder
whitelist it or put it there manually by [downloading the mod from here](https://github.com/soler91/noita-together/archive/mod.zip)

**Comment by darkblue12342** [comment]
I don´t even have an antivirus program. Windows defender/firewall has been turned off and it still didn`t work.

**Comment by soler91** [comment]
try installing https://www.microsoft.com/en-us/download/details.aspx?id=52685 or any newer versions if that's already installed
if all of that fails:
download firefox
copy the vcruntime140.dll into noita's folder (where logger.txt) is

**Comment by JeremyNGalloway** [comment]
Tried all steps above.
mods\noita-together\bin\pollnet.lua is present

Noita (Dec  1 2020) - 20210228-140304
-------------------------------------------
Lua (DoFile) error at 'mods/noita-together/init.lua': [string "mods/noita-together/files/lib/pollnet.lua"]:62: cannot load module 'mods\noita-together\bin\pollnet': The specified module could not be found.


Lua error: [string "mods/noita-together/init.lua"]:101: attempt to call global 'SendWsEvent' (a nil value)
Lua error: [string "mods/noita-together/init.lua"]:101: attempt to call global 'SendWsEvent' (a nil value)

**Comment by soler91** [comment]
@JeremyNGalloway [Download this](https://cdn.discordapp.com/attachments/813295603307642880/815474641019207730/vcruntime140.dll) and move it to your noita folder (where noita.exe is)

**Comment by JeremyNGalloway** [comment]
@soler91 This appears to have resolved the issue 👏 
Very much appreciated and thank you for NT <3

**Comment by darkblue12342** [comment]
Hi there, 
I am still having the same issue as before and unfortuneately none of the above changed anything :/

**Comment by darkblue12342** [comment]
I also tried using others sources and browsers, reinstalling my game or the mod, nothing has worked so far.

**Comment by soler91** [comment]
@darkblue12342 join our [discord server](https://discord.gg/ex3XFkXCgM) so we can work on your problem more quickly

**Comment by Cjumelin** [comment]
First, join the discord to be able to download the file,

Discord FAQ:

❓When starting a new game, it says there was an error initializing the mod? Game crashing ? Lobby not ready ?
Download [this](https://cdn.discordapp.com/attachments/813255004965044224/881622064002396250/vcruntime140.dll) and move it to your noita folder (where noita.exe is)

https://cdn.discordapp.com/attachments/813255004965044224/881622064002396250/vcruntime140.dll
