### ISSUE TITLE
Stuck on not ready

### ISSUE THREAD

**Issue by pepz136** [soler91/noita-together#24]
I have all the files needed and it just says "waiting for game" when I try to ready up, please help.

**Comment by soler91** [comment]
Does your game say "There were errors when initializing following mods: noita-together" when you start a new game ?

**Comment by pepz136** [comment]
> Does your game say "There were errors when initializing following mods: noita-together" when you start a new game ?

No

**Comment by pepz136** [comment]
> > Does your game say "There were errors when initializing following mods: noita-together" when you start a new game ?
> 
> No

OH NEVER MIND I GOT IT
