### ISSUE TITLE
[bug] Javascript error in main process

### ISSUE THREAD

**Issue by jonas8217** [soler91/noita-together#28]
First time i tried to run Noita Together this js error occurred:
Error: spawn powershell.exe ENOENT

![Error](https://i.imgur.com/NEktsGz.png)

I've messed with powershell Execution policies before, but i wouldn't know how to fix it, 
I've also removed quite a bit of AppxPackages, 
so if it's an easy fix on my part please do tell.

**Comment by soler91** [comment]
should be resolved with the latest update (v0.9.22)

**Comment by Navinate** [comment]
![image](https://user-images.githubusercontent.com/17831684/111017366-1d44cc80-8381-11eb-9755-f240b416405e.png)
I just downloaded the v0.9.22 version and got the same error

**Comment by soler91** [comment]
pushed another update, let me know if it persist

**Comment by jonas8217** [comment]
Version 0.9.23 fixes this problem.
