### ISSUE TITLE
[Bug] Group died, but lowest player didn't die.

### ISSUE THREAD

**Issue by BastiaanBekooij** [soler91/noita-together#29]
What happened:
0. Playing with a group with respawn penalty, players that died twice were kicked.
1. Player A died.
2. Player B had only 25 max hp left.
3. Everyone's run ended, except for player B.
![shot_20210308-173657-204556021--641-3973-00131844](https://user-images.githubusercontent.com/31536320/110351502-307c3300-8035-11eb-83c0-cc71a1e87837.png)

**Comment by soler91** [comment]
should be fixed on latest update, comment again if the issue persists
