### ISSUE TITLE
[Bug] Javascript error when trying to login into Twitch

### ISSUE THREAD

**Issue by MMacconen** [soler91/noita-together#30]
Everytime I click the "Login to Twitch" button it opens up https://nt.unicast.link:42069/auth/login in my browser, then it askes me to allow the app to "make changes", I press yes, then I get javascript error 
![JavascriptError](https://user-images.githubusercontent.com/80835637/111481122-52636d00-873b-11eb-9ff7-008ee0f09c04.png)

**Comment by MMacconen** [comment]
My brother has the same issue on his computer.

**Comment by soler91** [comment]
Not a bug, also already resolved
had forgotten to restart the backend after renewing the certificates
