### ISSUE TITLE
Perks arent being shared?

### ISSUE THREAD

**Issue by whompwhomp** [soler91/noita-together#31]
I have played with a a few different friends over the past few days, and I have never been able to get perks to be shared across the party.  I have checked the setting on the app and we are all playing on the beta branch.

**Comment by soler91** [comment]
did you check what the tooltip for the team perks say?
not all perks are shared, eventually it will be user configurable but not for now

**Comment by whompwhomp** [comment]
ok that makes sense, what perks are shared for now though? i have played a few times and none of the perks have been sharing at all

**Comment by soler91** [comment]
Greed
Never skip leg day
More blood
Stronger hearts
Attract gold
Extra shop item
More hate
More love
Peace with the gods
