### ISSUE TITLE
Are there issues with installing Noita to D: instead of C:?

### ISSUE THREAD

**Issue by AlligatorScrublord** [soler91/noita-together#36]
I just don't know how to join my own server because I don't see anything that indicates it's multiplayer when I launch Noita, and I can't find anything about this in FAQ or How To Use.

**Comment by AlligatorScrublord** [comment]
There also don't appear to be any launch buttons on the program itself.

**Comment by AlligatorScrublord** [comment]
Apparently you just have to enable Noita Together in the mod menu, you could've told me that.

**Comment by clragon** [comment]
it does, right [here](https://github.com/soler91/noita-together/wiki/Usage#in-game-things) in the wiki though.

**Comment by AlligatorScrublord** [comment]
Hey, I closed this request, no need to let me live with this shame.
