### ISSUE TITLE
architecture.md

### ISSUE THREAD

**Issue by jackhamby** [soler91/noita-together#4]
would you consider adding an architecture readme to help contributing devs get up to speed?
https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html
ex: https://github.com/rust-analyzer/rust-analyzer/blob/d7c99931d05e3723d878bea5dc26766791fa4e69/docs/dev/architecture.md

**Comment by soler91** [comment]
I might do it but not in the near future since im still considering a lot of changes to be made and im too busy to write and update an extra doc but surely in the future 👌
