### ISSUE TITLE
[Request] - Add direct connect option, skip lobby & login (local server)

### ISSUE THREAD

**Issue by NoShelter** [soler91/noita-together#41]
After the router loads the /login page, it would be nice to have the ability to create a local server and use direct connect versus twitch and websocket connection to onlywands.com. Direct connect would skip the /lobby route and load the vRoomCreation component before routing the user to a room.

I ask because I have friends who do not want to use twitch and would prefer direct connection.

![noita-together-directconnect](https://user-images.githubusercontent.com/3959882/117057034-978b3080-ace2-11eb-9dd5-0a70616a3008.png)

**Comment by soler91** [comment]
its planned however not a priority to me at the moment
