### ISSUE TITLE
noob issue with noita toghether

### ISSUE THREAD

**Issue by anthracose** [soler91/noita-together#42]
hi
french people here, i will try my best to write correctly

nice work on noita together.
we try it with my friend, work fine for him
for me,  got this when lunching exe

v0.9.3 
  
Noita Together
[update] Self-update started (Branch: mod)

[update] Update check started (Server: 0)

[update] Update check failed (Server: 0): RequestError: self signed certificate in certificate chain

[update] Update check failed

[update] Self-update failed 

i search for hours on google, and found nothing that work.
found some "trail" about NPM or proxy.

i ve got Kaspersky antivirus, no other firewall

so i come here to ask directly

thx

**Comment by soler91** [comment]
Something in your computer (could also just be your ISP) might be redirecting your traffic thru another page with a self signed https certificate
are you able to use a different computer in your house ? or try with mobile data on the same computer and see if the problem persist

**Comment by anthracose** [comment]
Thx for this quick respond, 

my friend computer is next to mine and use the same isp and its work fine with him, so its definitely my computer.
i try to stop my antivirus and its the the same, 

have u got the code without the auto update ?

**Comment by soler91** [comment]
auto updates cant be disabled for the stability and integrity of the games, i would really advise you to look more into your issue as it could also affect your security in the long run
