### ISSUE TITLE
[feature] save twitch token

### ISSUE THREAD

**Issue by clragon** [soler91/noita-together#44]
the program currently requires you to authenticate everytime you open it.

It would be nice if it would only request an authentication when necessary,   
e.g. by saving the twitch token and only requesting a new one when twitch rejects the saved one / it expired.

I do not know if this is actually possible, but I thought it would be really nice to have in case it is.

**Comment by soler91** [comment]
it is possible, in fact its been half implemented since the first release (its not twitch token btw)
will try to finish it some time soon since i lost a lot of changes i hadn't released due to a dead drive :+1:

**Comment by soler91** [comment]
added in v0.9.31
