### ISSUE TITLE
App launch from browswer not working

### ISSUE THREAD

**Issue by Elimitless** [soler91/noita-together#45]
When launching Noita Together, after being signed in to Twitch and authorizing the the notia together connection, the application does not launch from any browser. 

On Firefox I get this message and on Microsoft Edge nothing happens.
![image](https://user-images.githubusercontent.com/20347277/123974130-3b0a6180-d971-11eb-9665-2abc61fada43.png)

The very first time that Noita Together was launched, after clicking the login to twitch button, I do recall seeing a window pop up and disparage very quickly , it looked like the window that asks you what program you want to use to launch an application. But that only happened once. 

On the debug screen in firefox, it said that the link (https://nt.unicast.link:42069/auth/ticket) was an unknown protocol.
I have attempted to add a protocol handler for what I assumed the application was trying to use (.link) but that didn't work either.

**Comment by soler91** [comment]
Protocol is noitatogether://
reinstall the app while being on an administrator windows account, its an issue with electron

**Comment by Elimitless** [comment]
> 
> 
> Protocol is noitatogether://
> reinstall the app while being on an administrator windows account, its an issue with electron

I tried that. Does this link run a script with a custom protocol?

**Comment by Elimitless** [comment]
> 
> 
> Protocol is noitatogether://
> reinstall the app while being on an administrator windows account, its an issue with electron

I tried reinstalling on an administrator account yesterday. Does this protocol need to launch Noita Together or just Noita?

**Comment by soler91** [comment]
it needs to launch noita together

**Comment by Elimitless** [comment]
Also does the installer add protocols to the system registry?

**Comment by Elimitless** [comment]
Fixed.

in the firefox address bar type in about:support and then under Application Basics click Open Folder
![image](https://user-images.githubusercontent.com/20347277/124013642-67d16f80-d997-11eb-93b0-e56f09a5f768.png)
in that directory find and edit handlers.json and add this line to the "schemes" section. 
![image](https://user-images.githubusercontent.com/20347277/124014287-2d1c0700-d998-11eb-86be-8a25743a86ba.png)
then save the file and restart firefox and Noita Together again.
