### ISSUE TITLE
(Gameplay Feature) Share Fungal Shifts

### ISSUE THREAD

**Issue by DrySoldier** [soler91/noita-together#49]
When one user fungal shifts something, the change happens to all other users in the lobby

**Comment by djradnad** [comment]
Had a similar idea but this issue exists already so I’ll put here.

I was thinking it would be cool if the fungal shifts and recipes were random for all players in the seed, similar to how nt randomizes the perk deck and all other items.

**Comment by soler91** [comment]
this got added yay, slightly buggy atm since cooldown isnt synced properly but hey 😉
