### ISSUE TITLE
https://nt.unicast.link:42069/auth/login not working properly.

### ISSUE THREAD

**Issue by Riley-L-SV** [soler91/noita-together#53]
When I hit "login with Twitch.tv," Noita Together opens my browser and brings me to https://nt.unicast.link:42069/auth/login. After a moment, the page loads and I get the error message 
"hi dev big fan InternalOAuthError: Failed to obtain access token (status: 400 data: {"status":400,"message":"Invalid authorization code"} )"

**Comment by soler91** [comment]
try going to
https://nt.unicast.link:42069/auth/logout
then
https://www.twitch.tv/settings/connections and disconnect Noita together then attempt to login again

**Comment by Riley-L-SV** [comment]
The first link brought me to a page with the error message: 
"hi dev big fan TypeError: Cannot read property 'id' of undefined"
After looking in the second link, Noita together is not yet connected to my twitch account.

**Comment by soler91** [comment]
and login still gives you the same error ?

**Comment by Riley-L-SV** [comment]
Yes. The error message for the "Login with Twitch.tv" is still the same.

**Comment by soler91** [comment]
have you tried going to the link on another browser ?

**Comment by Riley-L-SV** [comment]
I have now. On both google chrome and Microsoft edge, I receive the same error message.

**Comment by KCannotPlay** [comment]
Have you figured this out? I am facing the same issue sadly.

**Comment by soler91** [comment]
does the problem persist ?
