### ISSUE TITLE
Trying to login /w Twitch gives 502 Bad Gateway error

### ISSUE THREAD

**Issue by Szpoti** [soler91/noita-together#56]
## Description

After freshly installing the app with `Noita-Together-Setup-0.9.35.exe` that I downloaded under the release page, when I click on Login with Twitch.tv, it takes me to [https://noita-together.unicast.link/auth/login](https://noita-together.unicast.link/auth/login) and here I see the following:
**502 Bad Gateway
nginx**
![image](https://user-images.githubusercontent.com/54551879/147774036-d2359850-9d65-4640-bb48-b49b5f14c41b.png)

Any ideas what happend? Did the service went off?

**Comment by soler91** [comment]
lack of braincells made me wreck everything but should be back to working

**Comment by Szpoti** [comment]
Looks like it's working well now indeed, ty
