### ISSUE TITLE
A error in javascript when logging in

### ISSUE THREAD

**Issue by Mjam-0** [soler91/noita-together#58]
![ERROR](https://user-images.githubusercontent.com/85319788/151641470-9cf110b8-989c-43b6-9bfe-304ac9aa11e1.png)

this error happens whenever I try and login

**Comment by soler91** [comment]
is the error appearing instantly or is it after some time loading ?
if its not instant its just not able to connect to the server, something on your side

**Comment by Mjam-0** [comment]
oh ok I'll check it out, my internet is fine, so it might be something to do with what I'm doing, I'll close this if I get it working.

**Comment by soler91** [comment]
you want the app to already be open when you visit the link btw

**Comment by Mjam-0** [comment]
I know, I haven't got it to work, it might be an internet issue, I'm going to close this (:
