### ISSUE TITLE
Mod does not install

### ISSUE THREAD

**Issue by Yloran** [soler91/noita-together#6]
Hey,
I've some problem with the installation, might be a problem for others as well.

The installer itself works flawlessly, can log in etc, but I cannot see the mod itself ingame to enable it. According to the FAQ / install guide it should do it by itself and re-installing the whole thing does nothing (well, nothing visible).

I have the game on steam, but the game is / was installed on another drive than C:\. I since moved the install folder to C:\Program Files (x86)\Steam\steamapps\common\Noita\ but after running (and reinstalling) Noita Together it states everything is fine, updated, installed while it is not exactly the case. Do you have anything cached anywhere so I can reset the whole procedure and start from scratch, as it looks like the uninstaller does not delete everything. Maybe any log files I can look through or send you?

**Comment by Yloran** [comment]
Update: I downloaded Noita and your mod on another PC, everything went smooth and the mods folder conained the mod iself this time, which I have copied to my original PC and it works now.

**Comment by soler91** [comment]
nothing cached, try reinstalling the game, it uses window's registry to get your game path

i wouldnt recommend just copying the mod folder to your game since it **might** not install the mod updates automatically when there's a new version

**Comment by LucyKuzanai** [comment]
i got a similar issue here, no error message, i did tried uninstalling noita and install it fresh without any mods.

the noita together won't show up in the mod list in game (and same for the game files for the mod section of it). Also i don't have any option to enable unsafe mod, i might have activate this before (like in 2019) and i beleive that this option disapear once getting activated? correct me if i'm wrong on this one.

i can properly chat with others in the noita together apps and link my twitch account to it, but the mod won't be detected in-game.

got the game on steam aswell, again very similar to Yloran issue, but i don't own another computer at home so i cannot do the same manipulation to "correct" the situation.

**Comment by soler91** [comment]
> 
> 
> i got a similar issue here, no error message, i did tried uninstalling noita and install it fresh without any mods.
> 
> the noita together won't show up in the mod list in game (and same for the game files for the mod section of it). Also i don't have any option to enable unsafe mod, i might have activate this before (like in 2019) and i beleive that this option disapear once getting activated? correct me if i'm wrong on this one.
> 
> i can properly chat with others in the noita together apps and link my twitch account to it, but the mod won't be detected in-game.
> 
> got the game on steam aswell, again very similar to Yloran issue, but i don't own another computer at home so i cannot do the same manipulation to "correct" the situation.
> 
> (On version 0.9.17)

is your game installed in the same drive as the app ?
if they are not in the same drive try reinstalling the app in the drive that has noita

**Comment by LucyKuzanai** [comment]
> is your game installed in the same drive as the app ?
> if they are not in the same drive try reinstalling the app in the drive that has noita

Originaly it wasn't no, but when i reinstalled the game and the app i did install them in the same drive (which is C drive), still no result. not used to noita mod system, but i did moded a lot of games before (mostly bethesda games and others like world of tanks, mass effect, etc.) i did more than double check your tutorial on how to instal and use the app, and i still don't see what i could have messed up. probably a windows thingy that does get in the way i guess.

BTW: i saw the video on youtube of this mod with dankorslam and McQueeb, you are a legend my dude, bringning "co-op"/"versus" to this awesome game.

**Comment by soler91** [comment]
@Yloran open windows powershell (windows key then type powershell if u dont know what that is)
then type this
`(Get-Item "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Steam App 881100").GetValue("InstallLocation")`
let me know what's the result from that

**Comment by LucyKuzanai** [comment]
> 
> 
> @Yloran open windows powershell (windows key then type powershell if u dont know what that is) woops meant to @LucyKuzanai
> then type this
> `(Get-Item "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Steam App 881100").GetValue("InstallLocation")`
> let me know what's the result from that

alright i'll do that this week and i'll come back with the result, i can't do it right now since my online class start in 10 minutes.
thanks for the support!

**Comment by LucyKuzanai** [comment]
@soler91 
i thought it was C drive but it's X, still the issue persist. uninstalled noita together app and reinstalling it on any of my drive (in alternation, whichever the letter for both app and game)

![noita together](https://user-images.githubusercontent.com/78818406/107448754-4d921480-6b10-11eb-945a-393f6041da2c.PNG)

**Comment by soler91** [comment]
@LucyKuzanai could you try having both noita and the app in the drive C ?

**Comment by Yloran** [comment]
Just out of curiosity I ran the PS command as well, my result was: 
D:\Steam\steamapps\common\Noita

Now the interesting thing is that I had noita on G:\ for a while now and it looks like steam did not overwrite this registry key when I moved it (and originally I installed it on D:\, not C:\). Even better, I've found the mod itself here lol. 

I'll try the following: I'll modify this key to point at another location (like desktop lol), and run Noita Together just to see what happens.

**Comment by Yloran** [comment]
![image](https://user-images.githubusercontent.com/78805186/107491813-f16cd600-6b8b-11eb-8f1a-8611e6682006.png)
Hahahaha, Okay, it works :D 

So solution would be, if you have moved Noita from your original install folder ever, via Steam, the Steam client just moves your game, BUT it does not rewrite the InstallLocation at
**HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 881100**, but instead it leaves the original location there. 

You either need to move it back where it was originally installed so the mod patching works as intended, or modify the InstallLocation key to the current one, as Steam does not do it. (Or copy the mod to the mod folders every time there's a new version from your original install location where only a mods folder exists lol)

Also, I moved it back yet again to G:\, deleted the manually copied mod from the mods folder, modified the registry key and ran Noita Together. The mod is there now, and will be patched from now on.

**Comment by soler91** [comment]
Glad to hear, guess ill have to try finding a better more reliable way of finding the game than using registry
