### ISSUE TITLE
Potions killing bank

### ISSUE THREAD

**Issue by TwilightKiddy** [soler91/noita-together#8]
I threw an ambrosia potion into bank, it made a breaking sound and broke the bank completely.

The panel with gold did not show up at all and neither me nor my partner could place things into it.

The only thing we could do is take out things that were placed there before that bottle.

**Comment by TwilightKiddy** [comment]
Tested this with a couple more potions, same effect every time.

**Comment by soler91** [comment]
are you both on the same branch ?
does the issue happen again if you completely close the game and the app and try on a new game?

**Comment by TwilightKiddy** [comment]
It persists even if you restart the game and start a new game. Reinstalling the mod seems to help, I'll try reproducing it again.

Yes, we both installed the mod via an installer approximately two hours ago.

**Comment by soler91** [comment]
i mean same branch of the game
also just making another another room or restarting the app should fix it, no need to reinstall anything

**Comment by TwilightKiddy** [comment]
Yep, made a completely fresh run and threw a starting potion into bank in the first holy mountain. Same. And I have a screenshot of the weird thing that's happening with the interface.
![image](https://user-images.githubusercontent.com/36814908/107431186-27cc3600-6b37-11eb-9dde-f3561f702509.png)

**Comment by TwilightKiddy** [comment]
Double checked the game version. We are both on Dec 1 2020 - 15:56:41.

**Comment by soler91** [comment]
interesting open your mods folder then go back one folder, upload logger.txt file to pastebin and link it here please

**Comment by TwilightKiddy** [comment]
Here you go.
https://pastebin.com/MBB59DYJ

**Comment by soler91** [comment]
So it turns out the function to get the material name for the contents of the flask is not yet on the main branch, i will push an update in a couple hours after my internet stops messing around but if you want to resolve it quickly switch to the beta branch of the game

**Comment by TwilightKiddy** [comment]
Yep, switched to beta, all working properly.

**Comment by soler91** [comment]
alright then thanks for reporting 👍
