### ISSUE TITLE
Unable to start the run

### ISSUE THREAD

**Issue by Radule6** [soler91/noita-together#84]
After installing noita together, after adding privileges' to the noita together mod and starting the game with active mods.   After the world loads it says in the left bottom corner that the noita together mod failed to initialize. And in the Noita together app it always says that it is waiting for me to activate the mod even thought it is activated.
![Screenshot_1](https://user-images.githubusercontent.com/74006590/193088914-f0b6226f-f1d8-4935-b423-6c05c454e86a.png)

**Comment by soler91** [comment]
From the faq on discord
❓When starting a new game, it says there was an error initializing the mod? Game crashing ? Lobby not ready ?
Download [this](https://cdn.discordapp.com/attachments/813255004965044224/881622064002396250/vcruntime140.dll) and move it to your noita folder (where noita.exe is)
