### ISSUE TITLE
Hosting a save

### ISSUE THREAD

**Issue by TwilightKiddy** [soler91/noita-together#9]
When hosting a saved game the host has their controls avaliable before you hit "Start Run" in the app, thus breaking quite everything. No bank, no shared hearts, etc.

**Comment by soler91** [comment]
does clicking the start run button fix it ?

**Comment by TwilightKiddy** [comment]
It starts the run for those who joined, but not for the host.

**Comment by soler91** [comment]
as long as the bank shows back for the host the run is indeed "started" again just no message, does the bank show after the host clicks to start the run again ?

**Comment by TwilightKiddy** [comment]
We gave up on that run, tried making another one and tried saving and loading a fresh world. Did not reproduce.
